


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace Entt.Entities
{ 
    public static partial class ViewDelegates 
    {
        public delegate void ApplyIn0Out1<TEntityKey, T1>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out1<TEntityKey, in TContext, T1>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out2<TEntityKey, T1, T2>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out2<TEntityKey, in TContext, T1, T2>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out1<TEntityKey, T1, T2>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out1<TEntityKey, in TContext, T1, T2>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out3<TEntityKey, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2, ref T3 r3 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out3<TEntityKey, in TContext, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2, ref T3 r3 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out2<TEntityKey, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2, ref T3 r3 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out2<TEntityKey, in TContext, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2, ref T3 r3 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn2Out1<TEntityKey, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, ref T3 r3 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn2Out1<TEntityKey, in TContext, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, ref T3 r3 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out4<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out4<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out3<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out3<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn2Out2<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn2Out2<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn3Out1<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn3Out1<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out5<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out5<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out4<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out4<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn2Out3<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn2Out3<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn3Out2<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn3Out2<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn4Out1<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn4Out1<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out6<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out6<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out5<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out5<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn2Out4<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn2Out4<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn3Out3<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn3Out3<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn4Out2<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn4Out2<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn5Out1<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, ref T6 r6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn5Out1<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, ref T6 r6 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn0Out7<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn0Out7<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        ref T1 r1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn1Out6<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn1Out6<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, ref T2 r2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn2Out5<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn2Out5<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, ref T3 r3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn3Out4<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn3Out4<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, ref T4 r4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn4Out3<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn4Out3<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, ref T5 r5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn5Out2<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn5Out2<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, ref T6 r6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void ApplyIn6Out1<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, ref T7 r7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContextIn6Out1<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, ref T7 r7 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, in T7 c7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, in T7 c7 )
            where TEntityKey: IEntityKey;
    }
}